name: Frontend Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend   # Adjust the directory according to your project structure
          npm install

      - name: Build CSS
        run: |
          cd frontend   # Adjust the directory according to your project structure
          npm run build:css

      - name: Build JSX
        run: |
          cd frontend   # Adjust the directory according to your project structure
          npm run build:jsx
 
