name: Full Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies for frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Run frontend tests
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Install dependencies for backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          npm test
