name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend and Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to build the frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Step to build the backend
      - name: Build Backend
        run: |
          cd backend
          npm install

      # Step to build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker tag my-app:latest my-app:main

      # Step to login to Docker Hub (replace with your Docker Registry)
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step to push Docker image to Docker Hub (replace with your Docker Registry)
      - name: Push Docker image
        run: |
          docker push my-app:latest
          docker push my-app:main
