name: Frontend Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies before running the build commands
      - name: Install dependencies
        run: npm install
        working-directory: ./review-application/frontend   # Adjust the directory according to your project structure

      # Build CSS and JSX after installing dependencies
      - name: Build CSS and JSX
        run: |
          # Replace these commands with your build commands for CSS and JSX
          npm run build:css
          npm run build:jsx
        working-directory: ./review-application/frontend   # Adjust the directory according to your project structure
